export const SIGN_IN = 'SIGN_IN';
export const LOG_OFF = 'LOG_OFF';
export const SET_UP_GOOGLE_AUTHENTICATION_API = 'SET_UP_GOOGLE_AUTHENTICATION_API';

export const CHECK_VIDEOS = 'CHECK_VIDEOS';
export const GET_SAVED_VIDEOS = 'GET_SAVED_VIDEOS';
export const SAVE_VIDEOS = 'SAVE_VIDEOS';
export const REMOVE_VIDEOS = 'REMOVE_VIDEOS';
export const RECOVER_VIDEOS = 'RECOVER_VIDEOS';
